### PR TITLE
Make paths to files configurable

### LINKED ISSUE #3: Hardcoded binary paths fail in certain environments
I'm testing goslmailer in my [slurm-gcp](https://github.com/schedmd/slurm-gcp)-based cluster. The system setup differs from the one you've used to develop goslmailer, and therefore some hardcoded paths can't be found causing (somewhat) silent failures.

I've successfully generated an email from a job by changing the following lines to fit my environment:

- https://github.com/CLIP-HPC/goslmailer/blob/5189f278eae40b4a74117a0afe40ee20fb9520de/internal/lookup/lookup.go#L24
- https://github.com/CLIP-HPC/goslmailer/blob/5189f278eae40b4a74117a0afe40ee20fb9520de/internal/slurmjob/sacct.go#L227
- https://github.com/CLIP-HPC/goslmailer/blob/5189f278eae40b4a74117a0afe40ee20fb9520de/internal/slurmjob/sacct.go#L237

I'd be happy to work on an PR if you'd let me know what'd be your preferred way to make these paths configurable.

### PR DESCRIPTION
**Pull request by tdido**
Closes #3

### CODE REVIEW

**Comment by tdido** [comment]
Hey @pja237. Here's the initial attempt at this. I'd appreciate your comments before moving forward.

File: cmd/goslmailer/goslmailer.go [hunk 1]
```diff
@@ -31,9 +31,19 @@ func main() {
 		os.Exit(1)
 	}
 
+	// set default paths
```
Comment (pja237) [inline cmd/goslmailer/goslmailer.go:34]: This part feels like it should belong to the config package, perhaps in GetConfig() after unmarshalling, here:
https://github.com/CLIP-HPC/goslmailer/blob/main/internal/config/config.go#L26

Also it would be good to do an `if bin_paths[key] exist;  then do nothing, else set default.

Specially now that you moved logfile to paths, which i'm not sure i feel comfortable with? it's not really a binary whose path we need to work, i'd perhaps leave that one out of the map.

Comment (pja237) [reply cmd/goslmailer/goslmailer.go:34]: in the end, even if the paths: {} map is not specified in the config, those defaults should be set and goslmailer should proceed, now it fails with:

`panic: assignment to entry in nil map`

**Review by pja237 — COMMENTED** [review]
Could you also please add the new paths map to the annotated config example?

https://github.com/CLIP-HPC/goslmailer/blob/main/cmd/goslmailer/goslmailer.conf.annotated_example

File: cmd/goslmailer/goslmailer.go (hunk 1 above)
Comment (tdido) [reply cmd/goslmailer/goslmailer.go:34]: Yep the "global" paths structure was one of the things I couldn't make up my mind about. I'll revert it to only binaries.

Comment (pja237) [reply cmd/goslmailer/goslmailer.go:34]: Love how it looks now, would you also move the "test and set default paths"  to config.GetConfig()?

Comment (tdido) [reply cmd/goslmailer/goslmailer.go:34]: Yep, didn't get around to applying all of your suggestions yet but I've got them on my queue ;)

File: internal/config/config.go [hunk 2]
```diff
@@ -32,6 +33,19 @@ func (cc *ConfigContainer) GetConfig(name string) error {
 	if err != nil {
 		return err
 	}
+
+	// set default paths
+        defaultpaths := map[string]string{
+            "sacct": "/usr/bin/sacct",
+            "sstat": "/usr/bin/sstat",
+        }
+
```
[the remark this answers is not in the document]
Comment (tdido) [reply internal/config/config.go:42]: Right, yes, good point.

**Review by timeu — APPROVED** [review]
LGTM
